### ISSUE TITLE
how to fig No module named 'config.config

### ISSUE THREAD

**Issue by Authnt** [wangjunkai2022/auto_pikpak#3]
how to use this grammer，please teach me.

**Comment by wangjunkai2022** [comment]
Does the runtime syntax throw an exception?

**Comment by Authnt** [comment]
我看config是一个文件夹，里面有config这个文件，我按照直接运行就会报这个错，搜语法没见到这么用的，好像不是运行时库的问题

**Comment by wangjunkai2022** [comment]
设置运行时目录为mian.py所在文件夹 不然import会找不到文件。
配置文件最好替换conf.yml 中的api为自己的临时邮箱api   或编写一个自己的邮箱获取和读取。tg的去tg申请api

**Comment by Authnt** [comment]
一般运行时会在main.py所在的文件夹直接执行main.py，这样听您的回答是不够的吗，import会找不到文件，我需要在win环境变量中加入这个文件夹的路径吗，还是加入代码临时路径呢，配置文件的api我到时候修改看看改一下，最新的版本谷歌验证这个可以弄吗，还是要改代码

**Comment by wangjunkai2022** [comment]
按道理 cd到main.py路径下运行python main.py 会自动绑定此路径为workdir 如果在其他路径下需要添加 对应的import路径到此项目的跟路径。
或者 你可以安装vccode开发 在VS下我有传vs的启动程序并添加了运行路径

最新的google验证只能手动验证 现在没去弄全自动google验证。

**Comment by Authnt** [comment]
我一般是右键命令提示符，在对应文件夹下是相当于cd到main.py路径下，执行确实是ModuleNotFoundError: No module named 'config.config'，看起来没有做绑定此路径为workdir这一步，我到时候安装vccode试试，谢谢解答
